### ISSUE TITLE
Restricted access persists after logout

### ISSUE THREAD

**Issue by alanning** [lorensr/roles-restricted#1]
After a `Meteor.logout()`, `Meteor.connection._roles` still has its original values.

Tried `delete Meteor.connection._roles` in console but after a refresh of the browser on localhost:3000, the user is automatically logged back in in the restricted state again, even without the `?acc=token`.

How do I keep the user from automatically having restricted access again?  Where is it even coming from, not sure how its pulling the state back when the token isn't in the URL or on the connection.

**Comment by lorensr** [comment]
Sorry about that. It stores the token in LocalStorage to achieve these behaviors: 

https://github.com/lorensr/login-links#connectionlogin

```
login-links/connectionToken
login-links/tokenExpiration
```

For clearing, we need an `onLogout` hook on the client. It was added to meteor in `v1.3.3.1`. Is it alright if the minimum supported version of this package changes to that version?

**Comment by alanning** [comment]
No worries. It's an amazing package! Cool with me to change min required
version if you're up for fixing it. (We're running latest now. )

**Comment by lorensr** [comment]
Sounds good, will try to get to it tomorrow

**Comment by lorensr** [comment]
I'm still publishing for arch, but should be fixed in `v0.1.4` 💃

The addition:

https://github.com/lorensr/login-links/blob/master/client/login-links.js#L108-L110

The test:

https://github.com/lorensr/login-links/blob/master/tests/client/connectionLogin.js#L73-L92
